### ISSUE TITLE
Can't load the configuration of '../Tune-A-Video/checkpoints/stable-diffusion-v1-4' at stage s5

### ISSUE THREAD

**Issue by nelson616** [text2cinemagraph/text2cinemagraph#7]
Hi, I used Google Colab with V100 (24GB RAM) to run inference_t2c.py file.
I followed the same instructions to setup the environment (using conda to create virtual environment) and downloaded necessary pretrained models. Everything was fine until stage s5 (optical flow part). I got the following error messages: 

Traceback (most recent call last):
  File "/content/text2cinemagraph/inference_t2c.py", line 149, in <module>
    main()
  File "/content/text2cinemagraph/inference_t2c.py", line 139, in main
    predict_flow(exp_config)
  File "/content/text2cinemagraph/test_motion.py", line 79, in predict_flow
    model = create_model(opt)
  File "/content/text2cinemagraph/models/models.py", line 13, in create_model
    model.initialize(opt)
  File "/content/text2cinemagraph/models/pix2pixHD_model.py", line 45, in initialize
    self.text_encoder = CLIPTextModel.from_pretrained(pretrained_model_path, subfolder="text_encoder")
  File "/usr/local/envs/t2c/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2079, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/envs/t2c/lib/python3.9/site-packages/transformers/models/clip/configuration_clip.py", line 134, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/envs/t2c/lib/python3.9/site-packages/transformers/configuration_utils.py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/envs/t2c/lib/python3.9/site-packages/transformers/configuration_utils.py", line 641, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of '../Tune-A-Video/checkpoints/stable-diffusion-v1-4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '../Tune-A-Video/checkpoints/stable-diffusion-v1-4' is the correct path to a directory containing a config.json file.

Is this a PATH problem or anything (model or config) I have to download as well?
Really appreciate your help!

**Comment by text2cinemagraph** [comment]
Hi @nelson616 ! This error is caused because I forgot to change the default paths in `options` from my local folder.
 To resolve the error for now you you can update the followign lines in `options/base_option.py` 

```
self.parser.add_argument('--tokenizer_path', type=str, default='../Tune-A-Video/checkpoints/stable-diffusion-v1-4')
self.parser.add_argument('--text_encoder_path', type=str, default='../Tune-A-Video/checkpoints/stable-diffusion-v1-4')
```

to 

```
self.parser.add_argument('--tokenizer_path', type=str, default='.checkpoints/stable-diffusion-v1-4')
self.parser.add_argument('--text_encoder_path', type=str, default='checkpoints/stable-diffusion-v1-4')
```

I will update it in the code. Thanks for pointing this error
